---
# user-service DB credentials
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: opentraum
  labels:
    app: user-service
    app.kubernetes.io/part-of: opentraum
    app.kubernetes.io/component: user
type: Opaque
stringData:
  username: "opentraum"
  password: "opentraum123!"
