apiVersion: v1
kind: Service
metadata:
  name: opentraum-redis
  namespace: opentraum
  labels:
    app: opentraum-redis
    app.kubernetes.io/part-of: opentraum
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app: opentraum-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
