apiVersion: v1
kind: Service
metadata:
  name: opentraum-kafka
  namespace: kafka
  labels:
    app: opentraum-kafka
    app.kubernetes.io/part-of: opentraum
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  selector:
    app: opentraum-kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      protocol: TCP
