apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: opentraum
  labels:
    app: reservation-service
    app.kubernetes.io/part-of: opentraum
    app.kubernetes.io/component: reservation
spec:
  type: ClusterIP
  selector:
    app: reservation-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
