apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: opentraum
  labels:
    app: auth-service
    app.kubernetes.io/part-of: opentraum
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
