name: Create Harbor Secret

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: AWS 자격증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: kubeconfig 설정
        run: |
          aws eks update-kubeconfig \
            --name skala3-cloud1-team8 \
            --region ap-northeast-2

      - name: harbor-secret 생성
        run: |
          kubectl create secret docker-registry harbor-secret \
            -n opentraum \
            --docker-server=${{ secrets.HARBOR_REGISTRY }} \
            --docker-username=${{ secrets.HARBOR_USERNAME }} \
            --docker-password=${{ secrets.HARBOR_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply --validate=false -f -
